-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2020-01-17 10:54:00.635

-- tables
-- Table: ACH_ADDITIVE
CREATE TABLE ACH_ADDITIVE (
    ID_ADDITIVE int  NOT NULL,
    NAME varchar(255)  NOT NULL,
    PRICE float(8)  NOT NULL,
    CONSTRAINT ACH_ADDITIVE_pk PRIMARY KEY  (ID_ADDITIVE)
);

-- Table: ACH_CUSTOMER
CREATE TABLE ACH_CUSTOMER (
    ID_CUSTOMER int  NOT NULL,
    NAME varchar(255)  NOT NULL,
    SURNAME varchar(255)  NOT NULL,
    TELEPHONE int  NOT NULL,
    STREET varchar(255)  NOT NULL,
    HOME_NUMBER varchar(255)  NOT NULL,
    CITY varchar(255)  NOT NULL,
    POSTAL_CODE varchar(255)  NOT NULL,
    USER_LOGIN varchar(30)  NOT NULL,
    USER_PASS varchar(255)  NOT NULL,
    CONSTRAINT ACH_CUSTOMER_pk PRIMARY KEY  (ID_CUSTOMER)
);

-- Table: ACH_CUSTOMER_ALERGEN
CREATE TABLE ACH_CUSTOMER_ALERGEN (
    CUSTOMER_ALERGEN_ID int  NOT NULL,
    ACH_INGREDIENT_ID_INGREDIENT int  NOT NULL,
    ACH_CUSTOMER_ID_CUSTOMER int  NOT NULL,
    CONSTRAINT ACH_CUSTOMER_ALERGEN_pk PRIMARY KEY  (CUSTOMER_ALERGEN_ID)
);

-- Table: ACH_INGREDIENT
CREATE TABLE ACH_INGREDIENT (
    ID_INGREDIENT int  NOT NULL,
    NAME varchar(255)  NOT NULL,
    ALERGEN int  NOT NULL,
    CONSTRAINT ACH_INGREDIENT_pk PRIMARY KEY  (ID_INGREDIENT)
);

-- Table: ACH_ORDER
CREATE TABLE ACH_ORDER (
    ID_ORDER int  NOT NULL,
    ACH_CUSTOMER_ID_CUSTOMER int  NOT NULL,
    ORDER_DATE datetime  NOT NULL,
    ORDER_STATUS int  NOT NULL,
    PAYMENT_TYPE int  NOT NULL,
    CONSTRAINT ACH_ORDER_pk PRIMARY KEY  (ID_ORDER)
);

-- Table: ACH_ORDER_ADDITIVE
CREATE TABLE ACH_ORDER_ADDITIVE (
    AMOUNT int  NOT NULL,
    ACH_ADDITIVE_ID_ADDITIVE int  NOT NULL,
    ACH_ORDER_ID_ORDER int  NOT NULL
);

-- Table: ACH_ORDER_PIZZA
CREATE TABLE ACH_ORDER_PIZZA (
    AMOUNT int  NOT NULL,
    PIZZA_SIZE int  NOT NULL,
    PIZZA_DOUGH int  NOT NULL,
    ACH_ORDER_ID_ORDER int  NOT NULL,
    ACH_PIZZA_ID_PIZZA int  NOT NULL
);

-- Table: ACH_PIZZA
CREATE TABLE ACH_PIZZA (
    ID_PIZZA int  NOT NULL,
    NAME varchar(255)  NOT NULL,
    PRICE float(8)  NOT NULL,
    TYPE int  NOT NULL,
    CONSTRAINT ACH_PIZZA_pk PRIMARY KEY  (ID_PIZZA)
);

-- Table: ACH_PIZZA_COMPOSITION
CREATE TABLE ACH_PIZZA_COMPOSITION (
    PIZZA_COMPOSITION_ID int  NOT NULL,
    amount int  NOT NULL,
    ACH_PIZZA_ID_PIZZA int  NOT NULL,
    ACH_INGREDIENT_ID_INGREDIENT int  NOT NULL,
    CONSTRAINT ACH_PIZZA_COMPOSITION_pk PRIMARY KEY  (PIZZA_COMPOSITION_ID)
);

-- foreign keys
-- Reference: ACH_CUSTOMER_ALERGEN_ACH_CUSTOMER (table: ACH_CUSTOMER_ALERGEN)
ALTER TABLE ACH_CUSTOMER_ALERGEN ADD CONSTRAINT ACH_CUSTOMER_ALERGEN_ACH_CUSTOMER
    FOREIGN KEY (ACH_CUSTOMER_ID_CUSTOMER)
    REFERENCES ACH_CUSTOMER (ID_CUSTOMER);

-- Reference: ACH_CUSTOMER_ALERGEN_ACH_INGREDIENT (table: ACH_CUSTOMER_ALERGEN)
ALTER TABLE ACH_CUSTOMER_ALERGEN ADD CONSTRAINT ACH_CUSTOMER_ALERGEN_ACH_INGREDIENT
    FOREIGN KEY (ACH_INGREDIENT_ID_INGREDIENT)
    REFERENCES ACH_INGREDIENT (ID_INGREDIENT);

-- Reference: ACH_ORDER_ACH_CUSTOMER (table: ACH_ORDER)
ALTER TABLE ACH_ORDER ADD CONSTRAINT ACH_ORDER_ACH_CUSTOMER
    FOREIGN KEY (ACH_CUSTOMER_ID_CUSTOMER)
    REFERENCES ACH_CUSTOMER (ID_CUSTOMER);

-- Reference: ACH_ORDER_ADDITIVE_ACH_ADDITIVE (table: ACH_ORDER_ADDITIVE)
ALTER TABLE ACH_ORDER_ADDITIVE ADD CONSTRAINT ACH_ORDER_ADDITIVE_ACH_ADDITIVE
    FOREIGN KEY (ACH_ADDITIVE_ID_ADDITIVE)
    REFERENCES ACH_ADDITIVE (ID_ADDITIVE);

-- Reference: ACH_ORDER_ADDITIVE_ACH_ORDER (table: ACH_ORDER_ADDITIVE)
ALTER TABLE ACH_ORDER_ADDITIVE ADD CONSTRAINT ACH_ORDER_ADDITIVE_ACH_ORDER
    FOREIGN KEY (ACH_ORDER_ID_ORDER)
    REFERENCES ACH_ORDER (ID_ORDER);

-- Reference: ACH_ORDER_COMPOSITION_ACH_ORDER (table: ACH_ORDER_PIZZA)
ALTER TABLE ACH_ORDER_PIZZA ADD CONSTRAINT ACH_ORDER_COMPOSITION_ACH_ORDER
    FOREIGN KEY (ACH_ORDER_ID_ORDER)
    REFERENCES ACH_ORDER (ID_ORDER);

-- Reference: ACH_ORDER_PIZZA_ACH_PIZZA (table: ACH_ORDER_PIZZA)
ALTER TABLE ACH_ORDER_PIZZA ADD CONSTRAINT ACH_ORDER_PIZZA_ACH_PIZZA
    FOREIGN KEY (ACH_PIZZA_ID_PIZZA)
    REFERENCES ACH_PIZZA (ID_PIZZA);

-- Reference: ACH_PIZZA_COMPOSITION_ACH_INGREDIENT (table: ACH_PIZZA_COMPOSITION)
ALTER TABLE ACH_PIZZA_COMPOSITION ADD CONSTRAINT ACH_PIZZA_COMPOSITION_ACH_INGREDIENT
    FOREIGN KEY (ACH_INGREDIENT_ID_INGREDIENT)
    REFERENCES ACH_INGREDIENT (ID_INGREDIENT);

-- Reference: ACH_PIZZA_COMPOSITION_ACH_PIZZA (table: ACH_PIZZA_COMPOSITION)
ALTER TABLE ACH_PIZZA_COMPOSITION ADD CONSTRAINT ACH_PIZZA_COMPOSITION_ACH_PIZZA
    FOREIGN KEY (ACH_PIZZA_ID_PIZZA)
    REFERENCES ACH_PIZZA (ID_PIZZA);

-- End of file.

